package br.uniriotec.ppgi.leo.controller.nlp.srl;

import java.io.File;
import java.io.IOException;
import java.util.List;

import br.uniriotec.ppgi.leo.controller.nlp.CoNLL2008Parser;
import br.uniriotec.ppgi.leo.controller.run.SystemCaller;
import br.uniriotec.ppgi.leo.model.PreprocessedSentence;


/**
 * This class is responsible for calling a Semantic Role Labeler
 * that will process a group of POS-tagged sentences.
 * 
 * @author Felipe Leao
 *
 */
public class LTHSemanticRoleLabeler {
	
	
	@SuppressWarnings("unused")
	private static String LTH_SRL_ROOT = "";
	
	@SuppressWarnings("unused")
	private LTHSemanticRoleLabeler(){}
	
	public LTHSemanticRoleLabeler(String lth_srl_root){
		LTH_SRL_ROOT = lth_srl_root;
	}
	

	/**
	 * Method to invoke the SRL system LTH_SRL and annotate the input file 
	 * generated by tempInputFileBuilder.
	 * 
	 * @deprecated Not actually works due to limitations on JVM memory usage (stop responding).
	 * 
	 * @param preprocessedSentences
	 * @return
	 * @throws IOException
	 */
	public File annotateSRL(List<PreprocessedSentence> preprocessedSentences) throws IOException{
		File inputFile = CoNLL2008Parser.tempInputFileBuilder(preprocessedSentences);
		
		String invoke = "sh scripts/run.sh < "+inputFile.getAbsolutePath() + " > ../leo-lth_srl.output";
		SystemCaller.callSystemProccess(invoke);
		
		
		return null;
	}

}
